SHOW WAREHOUSES;

CREATE WAREHOUSE demo_warehouse
WITH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Demo warehouse for Snowflake training';


SHOW WAREHOUSES;

USE WAREHOUSE COMPUTE_WH;

--DECREASE COST BY LOWERING TIME BEFORE AUTO-SUSPENSION
ALTER WAREHOUSE DEMO_WAREHOUSE
SET AUTO_SUSPEND = 60; 

SHOW WAREHOUSES;

DROP WAREHOUSE DEMO_WAREHOUSE;